#Установка определенного типа данных
x = str("Hello World")	
print(x)
print(type(x)) 
x = int(20)	
print(x)
print(type(x)) 
x = float(20.5)	
print(x)
print(type(x)) 
x = complex(1j)
print(x)
print(type(x)) 
x = list(("apple", "banana", "cherry"))	
print(x)
print(type(x)) 
x = tuple(("apple", "banana", "cherry"))	
print(x)
print(type(x)) 
x = range(6)	
print(x)
print(type(x)) 
