x = dict(name="John", age=36)
print(x)
print(type(x)) 	
x = set(("apple", "banana", "cherry"))	
print(x)
print(type(x)) 
x = frozenset(("apple", "banana", "cherry"))	
print(x)
print(type(x)) 
x = bool(5)		
print(x)
print(type(x)) 
x = bytes(5)	
print(x)
print(type(x)) 	
x = bytearray(5)	
print(x)
print(type(x)) 
x = memoryview(bytes(5))
